"""add lookbook_entries table

Revision ID: 9f555a9db01c
Revises: dd5c4ca26344
Create Date: 2026-08-15 14:08:01.704147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f555a9db01c'
down_revision: Union[str, None] = 'dd5c4ca26344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eyebrow', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_placeholder', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lookbook_entries')
    # ### end Alembic commands ###
