"""add phone and address to inquiries

Revision ID: b0444c8d28b0
Revises: 364f6aeda67a
Create Date: 2026-08-08 23:45:21.058482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0444c8d28b0'
down_revision: Union[str, None] = '364f6aeda67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
