"""add delivery price to products and delivery cents to inquiries

Revision ID: c930afb84556
Revises: 9f555a9db01c
Create Date: 2026-08-16 15:57:11.010466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c930afb84556'
down_revision: Union[str, None] = '9f555a9db01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_cents', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('delivery_price_cents', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('delivery_price_cents')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('delivery_cents')

    # ### end Alembic commands ###
