"""add items and total_cents to inquiries

Revision ID: dd5c4ca26344
Revises: e7f36ea20a1e
Create Date: 2026-08-15 12:44:18.250024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd5c4ca26344'
down_revision: Union[str, None] = 'e7f36ea20a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('total_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('total_cents')
        batch_op.drop_column('items')

    # ### end Alembic commands ###
